/**
 * Enumeration of allowed community categories.
 *
 * These predefined values represent the only allowed categories for new
 * communities and are used for filtering and sorting in the Explore page and
 * search results.
 *
 * Must be one of these exact strings. Case-sensitive matching is not enforced;
 * the system normalizes to these canonical forms.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ECommunityCategory =
  | "Tech & Programming"
  | "Science"
  | "Movies & TV"
  | "Games"
  | "Sports"
  | "Lifestyle & Wellness"
  | "Study & Education"
  | "Art & Design"
  | "Business & Finance"
  | "News & Current Affairs"
  | "General";
