import { tags } from "typia";

/**
 * Simplified summary representation of community membership records for display
 * in the 'Recent Communities' list.
 *
 * This type provides key information about a user's community memberships
 * without requiring full membership records. It focuses on the data needed to
 * render the left sidebar Recent Communities list: the community name, last
 * interaction time, and the community identifier. This enables efficient
 * loading and display of the most recently active communities without full
 * database joins.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformCommunityPlatformUserCommunityISummary = {
  /**
   * The community the user is associated with.
   * {!!community_platform_communities.id!}.
   *
   * This reference links the membership record to the community entity,
   * ensuring data integrity and enabling efficient lookups of a user's active
   * communities.
   */
  community_id: string & tags.Format<"uuid">;

  /**
   * The unique name of the community being joined or associated with.
   *
   * This is included in the summary for immediate display without requiring a
   * separate lookup to the community entity. It should match the name in the
   * community_platform_communities table exactly.
   */
  community_name: string;

  /**
   * Timestamp of the user's most recent activity within this community. This
   * field is updated when the user joins, posts, comments, or votes. Used to
   * sort and maintain the 'Recent Communities' list with the most recently
   * active communities appearing first.
   *
   * This timestamp determines the ordering of the Recent Communities list in
   * the left sidebar. The most recent activity can be joining, posting,
   * commenting, or voting in that community, making this the primary
   * indicator of recent engagement.
   */
  last_interaction_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the membership relationship was established. This is
   * immutable once set.
   *
   * This mark when the user first joined the community. It is preserved even
   * when the user leaves and rejoins, maintaining a historical record of the
   * relationship.
   */
  created_at?: (string & tags.Format<"date-time">) | undefined;
};
