import { ICommunityPlatformUserRole } from "./ICommunityPlatformUserRole";

/**
 * Array of user role definitions.
 *
 * This type represents a collection of user role definitions that are returned
 * by the /communityPlatform/roles endpoint. It contains multiple instances of
 * ICommunityPlatformUserRole objects, each describing a distinct role (guest,
 * member, admin) in the system.
 *
 * Each role definition includes the role's unique identifier, role name (e.g.,
 * 'guest', 'member', 'admin'), and a detailed description of its permissions
 * and responsibilities within the platform.
 *
 * This array is used to provide client applications with a complete mapping of
 * the role-based access control system, enabling them to properly display
 * permission information and implement appropriate UI behaviors based on the
 * user's role.
 *
 * The order of roles in this array is not guaranteed to be meaningful; clients
 * should identify roles by their role_name property rather than position in the
 * array.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformUserRoleArray = ICommunityPlatformUserRole[];
