import { tags } from "typia";

import { IAuthorizationToken } from "./IAuthorizationToken";

/**
 * Guest account entity that represents unauthenticated users with read-only
 * access to public content. This table enforces that all operations requiring
 * authentication are blocked at the data layer, and no user-specific state is
 * persisted. Used to prevent unauthorized access to write operations.
 *
 * ### Description of `id` property:
 *
 * > Primary Key.
 *
 * > This field is a unique UUID identifier for each guest session. It allows the
 * > system to track individual guest interactions for analytics and rate limiting
 * > purposes. The UUID format ensures global uniqueness across distributed
 * > systems and is generated on the server when a guest session is initiated.
 *
 * > This identifier is ephemeral and not tied to any persistent user account. It
 * > is not used for authentication or authorization purposes, only for session
 * > tracking and abuse detection.
 *
 * > The UUID will be stored in the system's tracking database until the session
 * > expires, at which point it may be permanently deleted or stored in an archive
 * > for analytics.
 *
 * > No human-readable information is associated with this identifier, maintaining
 * > user anonymity as required by the platform's privacy policy.
 *
 * ### Description of `created_at` property:
 *
 * > Timestamp when the guest session began. This field tracks access time for
 * > analytics but does not store persistent user state.
 *
 * > This field records the exact date and time when a guest user first accessed
 * > the platform, using ISO 8601 format with timezone information. The timestamp
 * > is generated server-side at the moment the guest session is created via the
 * > /auth/guest/join endpoint.
 *
 * > This field is used for analytics to understand traffic patterns, including
 * > peak usage times and duration of guest visits. It helps evaluate the
 * > effectiveness of guest experiences in converting users to registered members.
 * > However, it does not store any persistent identity or user-specific
 * > preferences.
 *
 * > To protect user privacy, these timestamps are periodically aggregated and
 * > anonymized for reporting, and individual records are purged after a defined
 * > period as specified in the data retention policy.
 *
 * > The server uses Asia/Seoul timezone for all timestamp generation, as
 * > specified in the business requirements, ensuring consistency in user
 * > experience metrics and reporting.
 *
 * ### Description of `ip_address` property:
 *
 * > IP address of the guest user. Used for analytics and spam detection. Not used
 * > for authentication.
 *
 * > This field captures the public IP address of the guest user at the time of
 * > their session initiation. It is stored as a string without normalization or
 * > anonymization, which allows for granular analysis of geographic patterns,
 * > rate limiting, and detection of automated scraping bots.
 *
 * > The field is useful for identifying suspicious activity patterns such as
 * > multiple guest sessions from the same IP address, which may indicate
 * > automated bots. It also helps with regional analytics to understand where
 * > growth opportunities exist.
 *
 * > Importantly, this field is not used for authentication purposes. Guest users
 * > are anonymous and cannot perform any actions that require authentication, so
 * > the IP address is strictly an operational and security logging tool.
 *
 * > To comply with data privacy regulations, this field is stored in accordance
 * > with the platform's Data Retention Policy and will be automatically purged
 * > after a defined period (typically 30 days) unless an active investigation is
 * > ongoing.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformGuest = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /**
   * Timestamp when the guest session began. This field tracks access time for
   * analytics but does not store persistent user state.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * IP address of the guest user. Used for analytics and spam detection. Not
   * used for authentication.
   */
  ip_address?: string | undefined;
};
export namespace ICommunityPlatformGuest {
  /**
   * Authentication token and session information for temporary guest access.
   *
   * This schema defines the response structure returned after successfully
   * establishing a guest session via the /auth/guest/join or
   * /auth/guest/refresh endpoints. It contains minimal identifying
   * information necessary to maintain the session while ensuring no personal
   * or persistent user data is exposed. The guest account provides read-only
   * access to public platform content and cannot perform interactive actions
   * like posting, commenting, or voting. All data points in this structure
   * are designed to be ephemeral and non-identifying.
   *
   * The session remains active only for the duration of the browsing session
   * and is automatically terminated when the user attempts to perform an
   * authentication-requiring action, at which point they are prompted to
   * login to become a member.
   */
  export type IAuthorized = {
    /**
     * Unique identifier of the guest session.
     *
     * This UUID serves as the persistent reference for the temporary guest
     * account created during the guest session. It is immediately generated
     * upon successful creation via the /auth/guest/join endpoint and is
     * used internally to track session state and analytics without
     * associating any permanent user identity or profile with the guest.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Timestamp when the guest session was created.
     *
     * This field records the exact moment a guest account was established,
     * tracked in ISO 8601 format with timezone. It is used for analytics
     * purposes to measure user acquisition trends, session duration
     * patterns, and spam detection. The value is automatically set by the
     * system and cannot be modified by the client.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Source IP address of the guest user.
     *
     * This field captures the public IP address from which the guest
     * session originated, stored as a string in standard IPv4 or IPv6
     * format. It is used for security analytics, abuse monitoring, and
     * regional content delivery. The value is collected automatically upon
     * session creation and remains immutable for the life of the session.
     * This data is not used for authentication or authorization purposes.
     */
    ip_address?: string | undefined;

    /** JWT token information for authentication */
    token: IAuthorizationToken;
  };
}
