import { tags } from "typia";

/**
 * Reference to the underlying member account that possesses admin privileges.
 * This links the admin record to its associated member account in the
 * community_platform_member table.
 *
 * The admin is not a separate identity but a privilege level granted to an
 * existing member. This relationship enforces that admin privileges are tied to
 * a specific user account with proper authentication credentials.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformAdminMemberId = string & tags.Format<"uuid">;
