import { tags } from "typia";

/**
 * Unique identifier for the admin record in UUID format. This is the primary
 * key for the admin table.
 *
 * Automatically generated by the system on admin privilege assignment and
 * remains immutable throughout the admin's tenure.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformAdminId = string & tags.Format<"uuid">;
