import { IPage } from "./IPage";
import { ICommunityPlatformMember } from "./ICommunityPlatformMember";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformMember = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ICommunityPlatformMember[];
};
export namespace IPageICommunityPlatformMember {
  /**
   * A page.
   *
   * Collection of records with pagination information.
   */
  export type ISummary = {
    /** Page information. */
    pagination: IPage.IPagination;

    /** List of records. */
    data: ICommunityPlatformMember.ISummary[];
  };
}
