import { IPage } from "./IPage";
import { ICommunityPlatformUserCommunity } from "./ICommunityPlatformUserCommunity";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformUserCommunity = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ICommunityPlatformUserCommunity[];
};
