import { tags } from "typia";

export interface GuestPayload {
  /**
   * Top-level user table ID (the fundamental user identifier in the system).
   * For guest roles, this will be a UUID generated by the JWT issuance system
   * representing the anonymous session identifier.
   */
  id: string & tags.Format<"uuid">;

  /** Discriminator for the discriminated union type. */
  type: "guest";
}
