import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformMemberIRequest } from "../../../../structures/ICommunityPlatformMemberIRequest";
import { IPageICommunityPlatformMember } from "../../../../structures/IPageICommunityPlatformMember";
import { ICommunityPlatformMember } from "../../../../structures/ICommunityPlatformMember";

/**
 * Search for member accounts with filtering and pagination.
 *
 * This endpoint provides comprehensive search and filtering capabilities for
 * member account records in the community_platform_member table. Unlike basic
 * retrieval operations, this PATCH method accepts complex search criteria in
 * the request body to find members based on multiple conditions.
 *
 * Member accounts represent authenticated users with full participation rights
 * including posting, commenting, and voting. Each record contains essential
 * user information like email, display_name, created_at, last_login_at, and a
 * soft delete flag (deleted_at) for account deactivation.
 *
 * The request body accepts a search criteria object that can filter by email
 * address (contains or exact match), display name (partial match), creation
 * date ranges, last login time, and account status (active/inactive). Results
 * are sorted by relevance, creation date, or login activity, and returned in
 * paginated format with 20 records per page.
 *
 * This operation is restricted to 'admin' roles only, as member account data
 * contains sensitive personal information. The email, display_name, and login
 * activity data must be protected and only accessible to authorized moderators
 * for platform management and security audits.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for filtering
 *   member accounts
 * @path /communityPlatform/admin/members
 * @accessor api.functional.communityPlatform.admin.members.search
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function search(
  connection: IConnection,
  props: search.Props,
): Promise<search.Response> {
  return true === connection.simulate
    ? search.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...search.METADATA,
          path: search.path(),
          status: null,
        },
        props.body,
      );
}
export namespace search {
  export type Props = {
    /**
     * Search criteria and pagination parameters for filtering member
     * accounts
     */
    body: ICommunityPlatformMemberIRequest;
  };
  export type Body = ICommunityPlatformMemberIRequest;
  export type Response = IPageICommunityPlatformMember;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/admin/members",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/admin/members";
  export const random = (): IPageICommunityPlatformMember =>
    typia.random<IPageICommunityPlatformMember>();
  export const simulate = (
    connection: IConnection,
    props: search.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: search.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific member's profile information.
 *
 * This operation retrieves detailed information about a specific member from
 * the community_platform_member table. The endpoint allows authorized users to
 * view essential profile data including the member's email address, optional
 * display name, account creation timestamp, and last login information. This
 * endpoint supports both self-service profile access and administrative
 * inspection of member accounts.
 *
 * The operation is designed with privacy considerations in mind - sensitive
 * information such as password hashes are excluded from the response. Only
 * non-sensitive profile metadata is returned to ensure user privacy. The
 * response structure follows the standard API pattern of returning entity
 * information when accessing specific resource endpoints.
 *
 * This operation is critical for the platform's user management functionality.
 * It enables users to verify their account information and allows
 * administrators to audit member accounts when necessary. The operation
 * directly supports the requirement for user authentication and ownership
 * verification, ensuring that content creation and modification permissions can
 * be properly enforced based on authenticated user identity.
 *
 * @param props.connection
 * @param props.memberId Unique identifier of the target member account. This
 *   UUID must correspond to an existing record in the community_platform_member
 *   table.
 * @path /communityPlatform/admin/members/:memberId
 * @accessor api.functional.communityPlatform.admin.members.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the target member account. This UUID must
     * correspond to an existing record in the community_platform_member
     * table.
     */
    memberId: string & tags.Format<"uuid">;
  };
  export type Response = ICommunityPlatformMember;

  export const METADATA = {
    method: "GET",
    path: "/communityPlatform/admin/members/:memberId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/admin/members/${encodeURIComponent(props.memberId ?? "null")}`;
  export const random = (): ICommunityPlatformMember =>
    typia.random<ICommunityPlatformMember>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("memberId")(() => typia.assert(props.memberId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
